<?php

/* * *************************************************************
 * Extension Manager/Repository config file for ext: "google_charts"
 *
 * Auto generated by Extension Builder 2015-10-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 * ************************************************************* */

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Google Charts',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Stefan Kapitza',
	'author_email' => 'stefan.kapitza@gmx.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-8.9.99',
			'extbase' => '',
			'fluid' => '',
			'version' => '',
			'recycler' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
